name: Release with goreleaser
on:
  push:
    tags:
      - v*.*
jobs:
  releases-matrix-windows:
    name: Release Go Binary for windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        pre_command: "bash ./src/rice-assets.sh"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.16
        project_path: "./src"
        ldflags: "-s -w"
        
  releases-matrix-linux:
    name: Release Go Binary for linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [386, amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        pre_command: "bash ./src/rice-assets.sh"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.16
        project_path: "./src"
        ldflags: "-s -w"
        
  releases-matrix-darwin:
    name: Release Go Binary for darwin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        pre_command: "bash ./src/rice-assets.sh"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.16
        project_path: "./src"
        ldflags: "-s -w"
    
  releases-matrix-linux-withoutembedded:
    name: Release Go Binary for linux without any embedded files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [386, amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        pre_command: "bash ./src/rice-assets.sh"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.16
        project_path: "./src"
        ldflags: "-s -w"
        binary_name: swego-without-embedded
        
  releases-matrix-darwin-withoutembedded:
    name: Release Go Binary for darwin without any embedded files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        pre_command: "bash ./src/rice-assets.sh"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.16
        project_path: "./src"
        ldflags: "-s -w"
        binary_name: swego-without-embedded
